### PR TITLE
Uncutmaza add to Extension

### PR DESCRIPTION
**Pull request by Nexus-Gits**

### CODE REVIEW

**Comment by phisher98** [comment]
Have you taken this from HindiProvider Repo ?

**Comment by Nexus-Gits** [comment]
> Have you taken this from HindiProvider Repo ?

They removed it from their repo.

**Comment by jeyjai** [comment]
> He made one for NSFW, one for no NSFW, which frankly is a great idea. Might do that if I have time and I think it's worth it. Right now I don't think it's worth it

Noticed today that all NSFW extensions are gone from your repo, have you split it to it's own repo or just abandoned it completely? 
I'm wondering because your cornhub was of the ones actually working, the only one with high quality

**Comment by KillerDogeEmpire** [comment]
@jeyjai it was split into a different repo, however shortcode doesn't work so I'll fix it soon

**Pull request closed without merging**
